feat: 提交15.2.0 (Stage-2)构建

diff --git a/debian/patches/libgo-testsuite.diff b/debian/patches/libgo-testsuite.diff
--- a/debian/patches/libgo-testsuite.diff
+++ b/debian/patches/libgo-testsuite.diff
@@ -1,66 +1,76 @@
-# DP: Only run the libgo testsuite for flags configured in RUNTESTFLAGS
+# DP: Only run the libgo testsuite for flags configured in CHECK_MULTISUBDIRS
 
 --- a/src/libgo/Makefile.am
 +++ b/src/libgo/Makefile.am
-@@ -926,7 +926,7 @@ BUILDGOX = \
- 	$(SHELL) $(srcdir)/mvifdiff.sh $@.tmp `echo $@ | sed -e 's/s-gox/gox/'`
- 
- GOTESTFLAGS =
--GOBENCH = 
-+GOBENCH =
- 
- # Check a package.
- CHECK = \
-@@ -947,6 +947,12 @@ CHECK = \
+@@ -948,21 +948,29 @@ CHECK = \
  	$(MKDIR_P) $(@D); \
  	rm -f $@-testsum $@-testlog; \
  	files=`$(SHELL) $(srcdir)/match.sh --goarch=$(GOARCH) --goos=$(GOOS) --srcdir=$(srcdir)/go/$(@D) --extrafiles="$(extra_go_files_$(subst .,_,$(subst /,_,$(@D))))" $(matchargs_$(subst /,_,$(@D)))`; \
-+	run_check=yes; \
-+	MULTILIBDIR="$(MULTILIBDIR)"; \
-+	case "$$MULTILIBDIR" in /64|/x32) \
-+	  echo "$$RUNTESTFLAGS" | grep -q "$${MULTILIBDIR\#/*}" || run_check=; \
-+	esac; \
++	run_check=; \
++	if [ -z "$(MULTISUBDIR)" ] || echo "$$CHECK_MULTISUBDIRS" | grep -q "$(MULTISUBDIR)"; then \
++	  run_check=yes; \
++	fi; \
 +	if test "$$run_check" = "yes"; then \
  	if test "$(USE_DEJAGNU)" = "yes"; then \
  	  $(SHELL) $(srcdir)/testsuite/gotest --goarch=$(GOARCH) --goos=$(GOOS) --dejagnu=yes --basedir=$(srcdir) --srcdir=$(srcdir)/go/$(@D) --pkgpath="$(@D)" --pkgfiles="$$files" --testname="$(@D)" $(GOTESTFLAGS); \
  	elif test "$(GOBENCH)" != ""; then \
-@@ -962,6 +968,7 @@ CHECK = \
- 	    echo "FAIL: $(@D)" > $@-testsum; \
+ 	  $(SHELL) $(srcdir)/testsuite/gotest --goarch=$(GOARCH) --goos=$(GOOS) --basedir=$(srcdir) --srcdir=$(srcdir)/go/$(@D) --pkgpath="$(@D)" --pkgfiles="$$files" --bench="$(GOBENCH)" $(GOTESTFLAGS); \
+ 	else \
+ 	  if $(SHELL) $(srcdir)/testsuite/gotest --goarch=$(GOARCH) --goos=$(GOOS) --basedir=$(srcdir) --srcdir=$(srcdir)/go/$(@D) --pkgpath="$(@D)" --pkgfiles="$$files" $(GOTESTFLAGS) >>$@-testlog 2>&1; then \
+-	    echo "PASS: $(@D)" >> $@-testlog; \
+-	    echo "PASS: $(@D)"; \
+-	    echo "PASS: $(@D)" > $@-testsum; \
++	    echo "PASS: $(@D)$(MULTISUBDIR)" >> $@-testlog; \
++	    echo "PASS: $(@D)$(MULTISUBDIR)"; \
++	    echo "PASS: $(@D)$(MULTISUBDIR)" > $@-testsum; \
+ 	  else \
+-	    echo "FAIL: $(@D)" >> $@-testlog; \
++	    echo "FAIL: $(@D)$(MULTISUBDIR)" >> $@-testlog; \
+ 	    cat $@-testlog; \
+-	    echo "FAIL: $(@D)" > $@-testsum; \
++	    echo "FAIL: $(@D)$(MULTISUBDIR)" > $@-testsum; \
  	    exit 1; \
  	  fi; \
 +	fi; \
++	else \
++	echo "SKIP: $(@D)$(MULTISUBDIR)"; \
  	fi
  
  # Build all packages before checking any.
 --- a/src/libgo/Makefile.in
 +++ b/src/libgo/Makefile.in
-@@ -1044,7 +1044,7 @@ BUILDGOX = \
- 	$(SHELL) $(srcdir)/mvifdiff.sh $@.tmp `echo $@ | sed -e 's/s-gox/gox/'`
- 
- GOTESTFLAGS = 
--GOBENCH = 
-+GOBENCH =
- 
- # Check a package.
- CHECK = \
-@@ -1065,6 +1065,12 @@ CHECK = \
+@@ -1066,21 +1066,29 @@ CHECK = \
  	$(MKDIR_P) $(@D); \
  	rm -f $@-testsum $@-testlog; \
  	files=`$(SHELL) $(srcdir)/match.sh --goarch=$(GOARCH) --goos=$(GOOS) --srcdir=$(srcdir)/go/$(@D) --extrafiles="$(extra_go_files_$(subst .,_,$(subst /,_,$(@D))))" $(matchargs_$(subst /,_,$(@D)))`; \
-+	run_check=yes; \
-+	MULTILIBDIR="$(MULTILIBDIR)"; \
-+	case "$$MULTILIBDIR" in /64|/x32) \
-+	  echo "$$RUNTESTFLAGS" | grep -q "$${MULTILIBDIR\#/*}" || run_check=; \
-+	esac; \
++	run_check=; \
++	if [ -z "$(MULTISUBDIR)" ] || echo "$$CHECK_MULTISUBDIRS" | grep -q "$(MULTISUBDIR)"; then \
++	  run_check=yes; \
++	fi; \
 +	if test "$$run_check" = "yes"; then \
  	if test "$(USE_DEJAGNU)" = "yes"; then \
  	  $(SHELL) $(srcdir)/testsuite/gotest --goarch=$(GOARCH) --goos=$(GOOS) --dejagnu=yes --basedir=$(srcdir) --srcdir=$(srcdir)/go/$(@D) --pkgpath="$(@D)" --pkgfiles="$$files" --testname="$(@D)" $(GOTESTFLAGS); \
  	elif test "$(GOBENCH)" != ""; then \
-@@ -1080,6 +1086,7 @@ CHECK = \
- 	    echo "FAIL: $(@D)" > $@-testsum; \
+ 	  $(SHELL) $(srcdir)/testsuite/gotest --goarch=$(GOARCH) --goos=$(GOOS) --basedir=$(srcdir) --srcdir=$(srcdir)/go/$(@D) --pkgpath="$(@D)" --pkgfiles="$$files" --bench="$(GOBENCH)" $(GOTESTFLAGS); \
+ 	else \
+ 	  if $(SHELL) $(srcdir)/testsuite/gotest --goarch=$(GOARCH) --goos=$(GOOS) --basedir=$(srcdir) --srcdir=$(srcdir)/go/$(@D) --pkgpath="$(@D)" --pkgfiles="$$files" $(GOTESTFLAGS) >>$@-testlog 2>&1; then \
+-	    echo "PASS: $(@D)" >> $@-testlog; \
+-	    echo "PASS: $(@D)"; \
+-	    echo "PASS: $(@D)" > $@-testsum; \
++	    echo "PASS: $(@D)$(MULTISUBDIR)" >> $@-testlog; \
++	    echo "PASS: $(@D)$(MULTISUBDIR)"; \
++	    echo "PASS: $(@D)$(MULTISUBDIR)" > $@-testsum; \
+ 	  else \
+-	    echo "FAIL: $(@D)" >> $@-testlog; \
++	    echo "FAIL: $(@D)$(MULTISUBDIR)" >> $@-testlog; \
+ 	    cat $@-testlog; \
+-	    echo "FAIL: $(@D)" > $@-testsum; \
++	    echo "FAIL: $(@D)$(MULTISUBDIR)" > $@-testsum; \
  	    exit 1; \
  	  fi; \
 +	fi; \
++	else \
++	echo "SKIP: $(@D)$(MULTISUBDIR)"; \
  	fi
  
  
